name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag local
    - name: Run container
      run: docker run -it -v $PWD:/data  local
    - name: build code
      run: ls -al;  cd data; make 
